name: Refresh Badges Cache

on:
  push:
    branches:
      - main

jobs:
  purge-badges-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@4.2.2

      - name: Purge badges cache
        uses: Angrido/Purge-Camo-Cache@v1.0.0
        with:
          repository: 'Angrido/Angrido' 
          branch: 'main'
